name = "fumat"
version = "0.1.0"
license = "license"
author = "WaveHello"
maintainer = "jonathanm@vt.edu"
copyright = "Copyright 2025, WaveHello"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]

# stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
# stdlib = {path = "../../stdlib"}
stdlib = "*"
fortplot = { git = "https://github.com/krystophny/fortplot" }

[dev-dependencies]
# stdlib = {path = "../../stdlib"}

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"



